Bell.Grok.Web/Controllers/DirectionSectorController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;
using Bell.Grok.Business;
using Bell.Grok.ExcelDAL;
using Bell.Grok.Model;
using Bell.Grok.Services.Exceptions;
using Bell.Grok.Web.Helpers;
using Bell.Grok.Web.Services;

namespace Bell.Grok.Web.Controllers
{
    public class DirectionSectorController : Controller
    {
        private const string JsonFormat = "text/plain";
        private const string ExcelMimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private const string DefaultScheduleFileName = "Экспорт.xlsx";
        private const string RelativeTemplateFilePath = "ReportTemplates/Timesheet.xlsx";
        private const string AppDateRelativePath = "~/App_Data";

        /// <summary>
        /// Метод, возвращающий представление, для редактирование нормативной нагрузки станций  и  табелей учета времени
        /// </summary>
        /// <param name="id">Идентификатор объекта</param>
        /// <param name="code">Код объекта</param>
        /// <param name="filterBpa">Фильтр по БПА(-1 если невыбрано)</param>
        /// <param name="filterMktk">Фильтр по МКТК(-1 если невыбрано)</param>
        /// <returns>Представление, для редактирования нормативной нагрузки станций и табелей учета времени</returns>
        public ActionResult Index(int id, string code, int? filterBpa, int? filterMktk)
        {
            var model = new DirectionSectorViewModel();
            model.Id = id;
            model.Code = code;
            model.FilterBPAStandart = filterBpa;
            model.FilterMKTKStandart = filterMktk;

            if (string.IsNullOrWhiteSpace(code))
            {
                model.SectorName = "";
                model.DirectionName = "";
                Session["ParentNode"] = "";
                Session["SelectedNode"] = "";
            }
            else if (UnifiedTreeIdPrefixDictionary.TreeIdCodes.First(e => e.Value.Equals(code)).Key.Equals("Sector"))
            {
                var sectorRepository = new SectorRepository();
                var directionRepository = new DirectionRepository();
                var directionId = sectorRepository.GetDirectionId(id);
                model.SectorName = sectorRepository.GetSectorNameById(id);
                model.SectorId = id;
                model.DirectionName = directionRepository.GetDirectionNameById(directionId);
                Session["ParentNode"] = UnifiedTreeIdPrefixDictionary.TreeIdCodes["Direction"] + directionId;
                Session["SelectedNode"] = code + id;

            }
            else if (UnifiedTreeIdPrefixDictionary.TreeIdCodes.First(e => e.Value.Equals(code)).Key.Equals("Direction"))
            {
                var directionRepository = new DirectionRepository();
                model.SectorName = "";
                model.DirectionName = directionRepository.GetDirectionNameById(id);
                Session["ParentNode"] = "";
                Session["SelectedNode"] = code + id;
            }
            else
            {
                model.SectorName = "";
                model.DirectionName = "";
                Session["ParentNode"] = "";
                Session["SelectedNode"] = "";
            }

            //В данной версии тз привилегии на просмотр нормативов и планов выручки совпадают.
            //Но всё может измениться, посему заводим две переменные
            model.CanViewStandart = GrokRoleObjectsService.CanUserMakeAction(UserActions.Read,
                                                                             User.Identity.Name,
                                                                             DataObjects.StationStandardLoadTW);
            model.CanViewProceedsPlan = GrokRoleObjectsService.CanUserMakeAction(UserActions.Read,
                                                                             User.Identity.Name,
                                                                             DataObjects.StationPlannedRevenue);
            model.CanViewTimesheets = GrokRoleObjectsService.CanUserMakeAction(UserActions.Read,
                                                                               User.Identity.Name,
                                                                               DataObjects.Timesheet);

            return View(model);
        }

        /// <summary>
        /// Метод, возвращающий частичное представление для просмотра планов выручки участка
        /// </summary>
        /// <param name="sectorId">Идентификатор участка</param>
        /// <returns>Частичное представление для просмотра планов выручки участка</returns>
        [ChildActionOnly]
        [OutputCache(VaryByParam = "*", Duration = 11)]
        [RoleObjectAuthGrok(UserActions.Read, DataObjects.StationPlannedRevenue)]
        public ActionResult ProceedsPlansReview(int sectorId)
        {
            ViewBag.SectorId = sectorId;
            return PartialView();
        }

        /// <summary>
        /// Метод, возвращающий частичное представление для табелей учёта времени
        /// </summary>
        /// <param name="sectorId">Идентификатор участка</param>
        /// <returns>Частичное представление для табелей учёта времени</returns>
        [ChildActionOnly]
        [OutputCache(VaryByParam = "*", Duration = 11)]
        [RoleObjectAuthGrok(UserActions.Read, DataObjects.Timesheet)]
        public ActionResult Timesheet(int sectorId)
        {
            var httpRuntimeSection = ConfigurationManager.GetSection("system.web/httpRuntime") as HttpRuntimeSection;

            var sectorRepository = new SectorRepository();            
            var sectorModel = sectorRepository.GetSectorModelById(sectorId);

            ViewBag.SectorName = sectorModel.DirectionName + "-" + sectorModel.SectorName;
            ViewBag.SectorId = sectorId;

            ViewBag.MaxRequestLength = httpRuntimeSection != null
                                           ? httpRuntimeSection.MaxRequestLength
                                           : 4096;

            ViewBag.AreButtonsVisible = GrokRoleObjectsService.CanUserMakeAction(UserActions.Update,
                                                                               User.Identity.Name,
                                                                               DataObjects.Timesheet);

            ViewBag.IsUploadButtonVisible = GrokRoleObjectsService.CanUserMakeAction(UserActions.AttachDoc,
                                                                               User.Identity.Name,
                                                                               DataObjects.Timesheet);

            ViewBag.IsDeleteUploadButtonVisible = GrokRoleObjectsService.CanUserMakeAction(UserActions.DeleteAttachedDoc,
                                                                               User.Identity.Name,
                                                                               DataObjects.Timesheet);

            return PartialView();
        }

        /// <summary>
        /// Метод, возвращающий представление, для редактирование нормативной нагрузки станций
        /// </summary>
        /// <param name="id">Идентификатор объекта</param>
        /// <param name="code">Код объекта</param>
        /// <param name="filterBpa">Фильтр по БПА(-1 если невыбрано)</param>
        /// <param name="filterMktk">Фильтр по МКТК(-1 если невыбрано)</param>
        /// <returns>Представление, для редактирование нормативной нагрузки станций</returns>
        [RoleObjectAuthGrok(UserActions.Read, DataObjects.StationStandardLoadTW)]
        [OutputCache(VaryByParam = "*", Duration = 11)]
        public ActionResult EditStandart(int id, string code, int? filterBpa, int? filterMktk)
        {
            var model = new EditStandartViewModel();
            model.Id = id;
            model.Code = code;

            model.FilterBPAStandart = filterBpa ?? -1;
            model.FilterMKTKStandart = filterMktk ?? -1;

            UpdateStandarts(id, code, model);

            var needChangeFilter = false;
            if (!model.AllBPAStandartNames
                .Any(e => e.Value.Equals((model.FilterBPAStandart).ToString(CultureInfo.InvariantCulture))))
            {
                model.FilterBPAStandart = -1;
                needChangeFilter = true;
            }
            if (!model.AllMKTKStandartNames
                .Any(e => e.Value.Equals((model.FilterMKTKStandart).ToString(CultureInfo.InvariantCulture))))
            {
                model.FilterMKTKStandart = -1;
                needChangeFilter = true;
            }

            if (needChangeFilter)
            {
                UpdateStandarts(id, code, model);
            }

            model.CanEdit = GrokRoleObjectsService.CanUserMakeAction(UserActions.Update,
                                                                        User.Identity.Name,
                                                                        DataObjects.StationStandardLoadTW);

            return PartialView(model);
        }

        private void UpdateStandarts(int id, string code, EditStandartViewModel model)
        {
            var standartRepository = new StandartRepository();
            List<short> ticketsPerHourBpaList, ticketsPerHourMktkList;
                       
            var codeItem = UnifiedTreeIdPrefixDictionary.TreeIdCodes.FirstOrDefault(e => e.Value == code);
            if (codeItem.Key == "Sector")
            {
                ticketsPerHourBpaList = standartRepository.GetAllSectorStandartsByTerminalType(id, null, 
                                                                                               TerminalTypes.Bpa);

Bell.Grok.Web/Controllers/ProceedsPlanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Bell.Grok.Business;
using Bell.Grok.Model;
using Bell.Grok.Services.Exceptions;
using Bell.Grok.Web.Helpers;

namespace Bell.Grok.Web.Controllers
{
    public class ProceedsPlanController : Controller
    {
        private const string JsonFormat = "text/plain";

        #region AJAX

        /// <summary>
        /// Обработчик ajax-запроса от kendo-grid с планами выручки на чтение 
        /// </summary>
        /// <param name="page">Текущая страница</param>
        /// <param name="pageSize">Количество элементов на странице</param>
        /// <param name="orderby">Параметры сортировки</param>
        /// <param name="beginDate">Начальная дата (первое число начального месяца)</param>
        /// <param name="endDate">Конечная дата (первое число конечного месяца)</param>
        /// <param name="sectorId">Идентификатор участка</param>
        /// <param name="stationId">Идентификатор станции (глобальный без привязки к участку)</param>
        /// <returns>Список список планов выручки и их количество в формате JSON</returns>
        [RoleObjectAjaxAuthGrok(UserActions.Read, DataObjects.StationPlannedRevenue)]
        [HttpPost]
        public ActionResult ReadProceedsPlans(int page, int pageSize, string orderby, string beginDate, string endDate,
                                              int sectorId, int? stationId)
        {            
            var stationRepository = new StationRepository();
            var proceedsPlanRepository = new ProceedsPlanRepository();
                 
            try
            {
                DateTime firstTime, lastMonth;
                if (!DateTime.TryParse(beginDate, out firstTime))
                {
                    throw new Exception("Некорректное значение начального месяца интервала");
                }
                if (!DateTime.TryParse(endDate, out lastMonth))
                {
                    throw new Exception("Некорректное значение конечного месяца интервала");
                }
                var monthsList = DatesToMontsListConverter.ConvertDatesToMonthsList(firstTime, lastMonth);

                List<ProceedsPlanGridModel> plans;
                int itemsCount;

                //Если есть идентификатор станции
                if (stationId.HasValue)
                {
                    //Значит нужно сделать выборку планов выручки по станции
                    var sectorStationId = stationRepository.GetSectorStationId(stationId.Value, sectorId);                   
                    plans = proceedsPlanRepository.GetProceedPlansForPeriod(monthsList, sectorStationId, orderby);                    
                    itemsCount = plans.Count;                    
                }
                else
                {
                    //Иначе нужно сделать выборку планов выручки по участку
                    plans = proceedsPlanRepository.GetSectorProceedPlansForPeriod(monthsList, sectorId, orderby);
                    itemsCount = plans.Count;                   
                }                

                return Json(new
                {
                    Items = new PagedList<ProceedsPlanGridModel>(plans, page, pageSize, itemsCount),
                    Count = itemsCount
                });
            }
            catch (Exception e)
            {
                AppExceptionManager.HandleException(e);
                return Json(new { status = JsonStatuses.Error, message = e.Message }, JsonFormat);
            }
            
        }        

        /// <summary>
        /// Обработчик ajax-запроса от kendo-grid с планами выручки на редактирование 
        /// </summary>
        /// <param name="model">Объект модели плана выручки</param>
        /// <returns>Http-статус выполнения запроса и идентификатор отредактированной записи
        ///          в случае успеха </returns>
        [RoleObjectAjaxAuthGrok(UserActions.Update, DataObjects.StationPlannedRevenue)]
        [HttpPost]
        public HttpStatusCodeResult UpdateProceedsPlan(ProceedsPlanGridModel model)
        {
            var proceedsPlanRepository = new ProceedsPlanRepository();

            try
            {
                var id = model.StationMonthProceedsId == -1
                                ? proceedsPlanRepository.AddProceedsPlan(model)
                                : proceedsPlanRepository.UpdateProceedsPlan(model);                

                return new HttpStatusCodeResult(HttpStatusCode.OK, id.ToString());
            }
            catch (Exception e)
            {
                AppExceptionManager.HandleException(e);
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }                                        
        }        

        #endregion
    }
}

Bell.Grok.Web/Views/DirectionSector/EditStandart.cshtml
@model Bell.Grok.Model.EditStandartViewModel

<script src="~/Scripts/editstandart-page.js" type="text/javascript"></script>

<div id="getStandartRows-url" data-url="@Url.Action("GetStandartRows", "DirectionSector")"></div>
<div id="setStandartRows-url" data-url="@Url.Action("SetStandartRows", "DirectionSector")"></div>
<div id="this-url" data-url="@Url.Action("Index", "DirectionSector")"></div>
<div id="modelId" data-value="@Model.Id"></div>
<div id="modelCode" data-value="@Model.Code"></div>
<div id="modelCanEdit" data-value="@Model.CanEdit"></div>
<div id="modelFilterBPAStandart" data-value="@Model.FilterBPAStandart"></div>
<div id="modelFilterMKTKStandart" data-value="@Model.FilterMKTKStandart"></div>

<h2>Ввод нормативов значений нормальной нагрузки</h2>

@using (@Html.BeginForm())
{
    <fieldset>
        <legend>Фильтр</legend>
        <table class="invisible-table">
            <tr>
                <td>MKTK</td>
                <td>БПА</td>
            </tr>
            <tr>
                <td>
                    @Html.DropDownListFor(model => model.FilterMKTKStandart, Model.AllMKTKStandartNames, new { @class = "ddList", data_bind = "value: filterMktk" })
                </td>
                <td>
                    @Html.DropDownListFor(model => model.FilterBPAStandart, Model.AllBPAStandartNames, new { @class = "ddList", data_bind = "value: filterBpa" })
                </td>
            </tr>
        </table>
    </fieldset>

    <div data-role="grid"
        data-auto-bind="false"
        data-bind="source: standartRowsSource, events: { change: onSelectionChange, dataBound: onDataBound }"
        data-resizable="true"
        data-sortable='{ "mode": "single", "allowUnsort": false }'
        data-pageable='{ "messages": 
                                        { "display": "{0} - {1} из {2}",
                                            "empty": "Нет элементов для отображения",
                                            "page": "Страница",
                                            "of": "из {0}",
                                            "itemsPerPage": "элементов на страницу",
                                            "first": "К первой странице",
                                            "previous": "К предыдущей странице",
                                            "next": "К следующей странице",
                                            "last": "К последней странице",
                                            "refresh": "Обновить" }
                                    }' 
        data-selectable="multiple cell"
        data-columns='[    
                                            { "field": "StationName", "title": "Станция", "sortable" : true},
                                            { "field": "MKTK", "title": "МКТК", "sortable" : true},
                                            { "field": "BPA", "title": "БПА", "sortable" : true },  
                                        ]'
        id="mainGrid">
    </div>
    if (Model.CanEdit)
    {
    <div>
        <input type="button" value="Выбор всех станций" class="k-button button-top-indent" data-bind="click: selectAll" />
        <input type="button" value="Изменить" class="k-button button-top-indent" data-bind="click: сhange" accesskey='n' />
    </div>
    }

    <div id="change-popup" class="parent-window">
        <div>
            Введите значение норматива нагрузки для выбранных станций:
        </div>
        <br />
        <input id="changeInput" type="text" data-role="numerictextbox" data-format="#" data-decimals="0" data-min="0" data-max="999999" data-bind="value: changeValue" style="width: 98%" />
        <br />
        <input type="button" value="Ок" class="k-button button-top-indent" data-bind="click: changeSubmit" style="width: 49%" />
        <input type="button" value="Отмена" class="k-button button-top-indent" data-bind="click: changeReject" style="width: 49%" />
    </div>
}

Bell.Grok.Web/Views/DirectionSector/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Bell.Grok.Model.DirectionSectorViewModel

<script>
    var triggerActivateTab = function(selectedItem) {
        if (selectedItem.hasClass("timesheet-li")) {
            $(document).trigger("timesheetTabActivated");
            //Если скрипт с табелями ещё не прогрузился - то помечаем в разметке, 
            //что табели - по умолчанию активная вкладка
            $("#is-timesheet-tab-activated").attr("data-is-activated", "1");
        } else if (selectedItem.hasClass("proceed-plans-li")) {
            $(document).trigger("proceedPlansTabActivated");
            //Если скрипт с планами выручки ещё не прогрузился - то помечаем в разметке, 
            //что планы по выручке - по умолчанию активная вкладка
            $("#is-proceed-plans-activated").attr("data-is-activated", "1");
        } else if (selectedItem.hasClass("edit-standart-li")) {
            $(document).trigger("editStandartTabActivated");
            //Если скрипт с нормативами ещё не прогрузился - то помечаем в разметке, 
            //что нормативы - по умолчанию активная вкладка
            $("#is-edit-standart-activated").attr("data-is-activated", "1");
        }
    };

    $(document).ready(function () {
        var pageCode = $.urlParam("code");
        var directionSectorId = $.urlParam("id");

        $("#teller-tabstrip").kendoTabStrip({
            activate: function (e) {
                var selectedItem = $("#teller-tabstrip").data("kendoTabStrip").select();
                var currentIndex = selectedItem.index();                

                if (pageCode === "S") {
                    $.session.set('DirectionSectorTabStripCurrentIndex' + '-' + directionSectorId, currentIndex);
                }

                triggerActivateTab(selectedItem);
            }
        });
        
        var tabStrip = $("#teller-tabstrip").data("kendoTabStrip");
        if (tabStrip) {            
            var tabStripCurrentIndex = $.session.get('DirectionSectorTabStripCurrentIndex' + '-' + directionSectorId);

            if (tabStripCurrentIndex !== null &&
                tabStripCurrentIndex !== undefined) {
                tabStrip.select(tabStripCurrentIndex);
            } else if (tabStrip.items().length > 0) {
                tabStrip.select(0);
            }

            var savedSelectedItem = tabStrip.select();
            triggerActivateTab(savedSelectedItem);            
        }             
    });
</script>

<br />
<table class="invisible-table">
    <tr>
        <td class="label-text-aligment">
            @Html.LabelFor(model => model.DirectionName)
        </td>
        <td>
            @Html.TextBoxFor(model => model.DirectionName, new { @class = "k-input k-textbox k-state-disabled", disabled = "disabled" })
        </td>
    </tr>
    <tr>
        <td class="label-text-aligment">
            @Html.LabelFor(model => model.SectorName)
        </td>
        <td>
            @Html.TextBoxFor(model => model.SectorName, new { @class = "k-input k-textbox k-state-disabled", disabled = "disabled" })
        </td>
    </tr>
</table>
<br />

@if (Model.CanViewStandart || 
    (Model.SectorId.HasValue && Model.CanViewProceedsPlan) ||
    (Model.SectorId.HasValue && Model.CanViewTimesheets))
{
    <div id="teller-tabstrip" data-role="tabstrip" data-animation="false" data-bind="events:{ activate: tabStripActivateHandler}">
        <ul>
            @if (Model.CanViewStandart)
            {
                <li class="edit-standart-li k-state-active">Нормативные значения
                </li>
            }
            @if (Model.SectorId.HasValue && Model.CanViewProceedsPlan)
            {
                <li class="proceed-plans-li">Планы по выручке
                </li>
            }
            @if (Model.SectorId.HasValue && Model.CanViewTimesheets)
            {
                <li class="timesheet-li">Табель                    
                </li>
            }
        </ul>
        @if (Model.CanViewStandart)
        {
            <div>
                <div id="is-edit-standart-activated" data-is-activated="0"></div>
                @Html.Action("EditStandart", "DirectionSector", new { id = Model.Id, code = Model.Code, filterBpa = Model.FilterBPAStandart, filterMktk = Model.FilterMKTKStandart })
                <br />
            </div>
        }
        @if (Model.SectorId.HasValue && Model.CanViewProceedsPlan)
        {
            <div>
                <div id="is-proceed-plans-activated" data-is-activated="0"></div>
                @Html.Action("ProceedsPlansReview", "DirectionSector", new { sectorid = Model.SectorId.Value })
            </div>
        }
        @if (Model.SectorId.HasValue && Model.CanViewTimesheets)
        {
            <div>
                <div id="is-timesheet-tab-activated" data-is-activated="0"></div>
                @Html.Action("Timesheet", "DirectionSector", new { sectorid = Model.SectorId.Value })
            </div>            
        }
    </div>
}

Bell.Grok.Web/Views/DirectionSector/ProceedsPlansReview.cshtml
<script src="~/Scripts/proceeds-plans-review.js" type="text/javascript"></script>

<div id="read-proceeds-plan-url" data-url="@Url.Action("ReadProceedsPlans", "ProceedsPlan")"></div>
<div id="sector-id" data-value="@ViewBag.SectorId"></div>

<div id="proceeds-plan-container">
    <h3>Просмотр планов выручки по участкам производства</h3>
    <form id="proceeds-plan-search-params">
        <span>Планы выручки с</span>
        &nbsp;
        <input id="proceeds-plan-begin-date" name="proceedsPlanBeginDate" data-role="datepicker" data-bind="value: proceedsPlanBeginDate, events: { change: changeBeginMonth }" data-start="year" data-depth="year" data-format="MMMM yyyy" />
        &nbsp;
        <span>по</span>
        &nbsp;
        <input id="proceeds-plan-end-date" name="proceedsPlanEndDate" data-role="datepicker" data-bind="value: proceedsPlanEndDate, events: { change: changeEndMonth }" data-start="year" data-depth="year" data-format="MMMM yyyy" />
    </form>
    <div data-role="grid"
        data-auto-bind="false"
        data-bind="source: proceedsPlanSource, events: { dataBound: proceesdsPlanBound }"
        data-resizable="true"
        data-sortable='{ "mode": "single", "allowUnsort": false }'
        data-pageable='{ "messages": 
                        { "display": "{0} - {1} из {2}",
                            "empty": "Нет элементов для отображения",
                            "page": "Страница",
                            "of": "из {0}",
                            "itemsPerPage": "элементов на страницу",
                            "first": "К первой странице",
                            "previous": "К предыдущей странице",
                            "next": "К следующей странице",
                            "last": "К последней странице",
                            "refresh": "Обновить" }
                    }'
        data-columns='[    
                        { "field": "Date", "title": "Дата", "sortable" : true},
                        { "field": "CommonPlan", "title": "План общий", format: "{0:##,#}", "sortable" : true },
                        { "field": "PaidPlan", "title": "в т.ч. платный", format: "{0:##,#}", "sortable" : true}
                    ]'
        id="proceeds-plan-grid"
        style="width: 50%; margin-top: 20px;">
    </div>
</div>