Bell.Grok.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bell.Grok.Model;
using Bell.Grok.Web.Helpers;

namespace Bell.Grok.Web.Controllers
{
    /// <summary>
    /// Контроллер для меню администратора и сотрудника ОТиЗП
    /// </summary>
    [AjaxAuthGrok(Roles.Administrator, Roles.OTZPEmployee)]
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class MenuController : Controller
    {
        /// <summary>
        /// Метод, обрабатывающий ajax-звпрос от kendo-menu
        /// </summary>
        /// <returns>JSON с набором пунктов меню администратора и сотрудника ОТиЗП</returns>
        [HttpPost]
        public JsonResult GetActions()
        {
            if (User.IsInRole(Roles.Administrator.ToText()))
            {
                var adminMenuAttributes = GrokMenuProvider.GetItems(Url).Select(d => new
                    {
                        items = string.Empty,
                        text = d.ItemText,
                        url = d.ItemUrl
                    });

                return Json(
                    new
                        {
                            status = JsonStatuses.Ok,
                            items = adminMenuAttributes.ToArray(),
                            text = GrokMenuProvider.GetHeaderName()
                        });
            }

            if (User.IsInRole(Roles.OTZPEmployee.ToText()))
            {
                var adminMenuAttributes = GrokMenuProvider.GetWorkDepartmentItems(Url).Select(d => new
                {
                    items = string.Empty,
                    text = d.ItemText,
                    url = d.ItemUrl
                });

                return Json(
                    new
                    {
                        status = JsonStatuses.Ok,
                        items = adminMenuAttributes.ToArray(),
                        text = GrokMenuProvider.GetWorkDepartmentHeaderName()
                    });
            }

            return Json(new {});
        }

    }
}

Bell.Grok.Web/Controllers/SharedController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Bell.Grok.Business;
using Bell.Grok.Model;
using Bell.Grok.Web.ViewModel;
using Bell.Grok.Web.Helpers;

namespace Bell.Grok.Web.Controllers
{
    /// <summary>
    /// Контроллер разделяемых элементов
    /// </summary>
    public class SharedController : Controller
    {
        /// <summary>
        /// Метод, возвращающий частичное представление, отображающее состояние авторизованности пользователя (залогинен или нет)
        /// </summary>
        /// <returns>Частичное представление, отображающее состояние авторизованности пользователя</returns>
        [ChildActionOnly]
        public ActionResult LoginStatus()
        {
            return PartialView();
        }

        /// <summary>
        /// Метод, возвращающий частичное представление, отображающее дерево навигации
        /// </summary>
        /// <returns>Частичное представление, отображающее дерево навигации</returns>
        [ChildActionOnly]
        public ActionResult NavigationTree()
        {
            var scheduleRepository = new ScheduleRepository();
            var statuses = scheduleRepository.GetAllScheduleStatus();
            var model = new NavigationTreeModel();
            model.ScheduleStatuses = statuses.Select(a => a.ToSelectListItem()).ToList();
            model.ScheduleStatus = Session["ScheduleStatuses"] as List<string>;
            model.FilterEnabled = User.IsInRole(Roles.ProfessionalGroupOrganizer.ToText()) || User.IsInRole(Roles.SectorHead.ToText()) || User.IsInRole(Roles.OTZPEmployee.ToText());

            foreach (var status in model.ScheduleStatuses)
            {
                if (model.ScheduleStatus != null && model.ScheduleStatus.Any(e => e.Equals(status.Value))) status.Selected = true;
            }
            return PartialView(model);
        }

    }
}

Bell.Grok.Web/Views/Shared/LoginStatus.cshtml
<div id="logindisplay">
@if (User.Identity.IsAuthenticated)
{
    <span class="logindisplay-link">@User.Identity.Name</span>
    <a id="logout-link" href="@Url.RouteUrl("Logout")">Выход</a>
}
else
{ 
    <a href="@Url.RouteUrl("Login")">Войти</a>
}
</div>

Bell.Grok.Web/Views/Shared/NavigationTree.cshtml
@model Bell.Grok.Web.ViewModel.NavigationTreeModel
<div id="direction-tree">
    <div id="selected-node-unified-tree-id" data-unified-id="@Session["SelectedNode"]"></div>
    <div id="parent-node-unified-tree-id" data-unified-id="@Session["ParentNode"]"></div>
    <div></div>

    <div id="get-directions-url" data-get-directions-url="@Url.Action("ReadDirections", "Home")"></div>
    <div id="get-sectors-url" data-get-sectors-url="@Url.Action("ReadSectors", "Home")"></div>
    <div id="get-sectors-structure-url" data-get-sectors-structure-url="@Url.Action("ReadSectorStructure", "Home")"></div>
    <div id="get-stations-url" data-get-stations-url="@Url.Action("ReadStationsAndCashiersCharacters", "Home")"></div>
    <div id="get-home-after-change-date-url" data-home-after-change-date-url="@Url.Action("IndexAfterDateChange", "Home")"></div>
    <div id="get-cashiers-url" data-get-cashiers-url="@Url.Action("ReadCashiers", "Home")"></div>
    <div id="index-url" data-url="@Url.Action("Index", "Home")"></div>
    <div id="cashier-contract-datepicker-container">
        <div id="current-date" data-date="@Session["CurrentDate"]"></div>
        <span>Данные на </span>
        <input id="cashier-contract-datepicker" value="" style="width: 150px;" />
        <br/>
        <br/>
        @if (Model.FilterEnabled)
        {
            <div>
                <div>Фильтр по статусам расписаний</div>
                @Html.ListBoxFor(model => model.ScheduleStatus, Model.ScheduleStatuses, new {style="width:212px;"})
            </div>
        }
        <br/>
    </div>
    Направления |    
    <div id="treeview" class="ie9-scroll-fix"></div>
    @if (Model.FilterEnabled)
    {
        <script>
            $('#ScheduleStatus').kendoMultiSelect();

            var multiselectSpecializations = $("#ScheduleStatus").data("kendoMultiSelect");
            multiselectSpecializations.bind("change", function (e) {
                var result = $("#index-url").attr("data-url");
                var ids = $("#ScheduleStatus").data("kendoMultiSelect").value();
                if (ids.length > 0) {
                    result = result + "?";
                    for (var i = 0; i < ids.length - 1; i++) {
                        result = result + "scheduleStatuses=" + ids[i] + "&";
                    }
                    result = result + "scheduleStatuses=" + ids[ids.length - 1];
                }
                window.location.href = result;
            });

        </script>
    }
</div>

Bell.Grok.Web/Views/Shared/_Layout.cshtml
@using Bell.Grok.Web.Services
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/kendo/2013.3.1119/kendo.common.min.css" rel="stylesheet" />
    <link href="~/Content/kendo/2013.3.1119/kendo.default.min.css" rel="stylesheet" />

    <link href="~/Plugins/jquery-msg/jquery.msg.css" rel="stylesheet" type="text/css" />
    <link href="~/Plugins/jquery-loadmask-0.4/jquery.loadmask.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/2013.3.1119/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/2013.3.1119/cultures/kendo.culture.ru-RU.min.js")" type="text/javascript"></script>

    <script src="~/Plugins/jquery.pubsub/jquery.pubsub.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery-msg/jquery.center.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery-msg/jquery.msg.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.session/jquery.session.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.validate.hooks/jquery.validate.hooks.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.deserialize/jquery.deserialize.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery-loadmask-0.4/jquery.loadmask.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.scrollTo/jquery.scrollTo.min.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.parseparams/jquery.parseparams.js" type="text/javascript"></script>
    <script src="~/Plugins/jquery.fileDownload/jquery.fileDownload.js" type="text/javascript"></script>

    <script src="~/Scripts/menu.js" type="text/javascript"></script>
    <script src="~/Scripts/controller.js" type="text/javascript"></script>
    <script src="~/Scripts/json-status.js" type="text/javascript"></script>
    <script src="~/Scripts/schedule-status.js" type="text/javascript"></script>
    <script src="~/Scripts/utils.js" type="text/javascript"></script>
    <script src="~/Scripts/navigation-tree.js" type="text/javascript"></script>
    <script src="~/Scripts/validation-helper.js" type="text/javascript"></script>
    <script src="~/Scripts/numeric-text-box-title.js" type="text/javascript"></script>    
    <script src="~/Scripts/GrokExtention.js" type="text/javascript"></script>


    @RenderSection("Scripts", false)
    @IdleTimer.Register(SessingsService.GetIdleWaitTime())
    <script>
        //flag to check windows in unloading
        window.unloading = false;
        $(window).on('beforeunload', function () {
            window.unloading = true;
        });
    </script>
</head>
<body>
    <script type="text/javascript">
    </script>
    <div id="login-url" data-url="@Url.Action("Login", "Account")"></div>    
    <div id="is-user-authenticated" data-is-authenticated="@User.Identity.IsAuthenticated"></div>
    <div id="is-user-is-administrator" data-is-admin="@User.IsInRole("Администратор")"></div>
    <div id="current-controller" data-current-controller="@Request.RequestContext.RouteData.Values["controller"].ToString()"></div>
    <div id="page">
        <div id="header">
            <div>
                <span class="headerLogo">
                    <img src="~/Content/img/logo.png" />
                    <span>@Bell.Grok.Web.Resources.GROK.ProductVersion</span>
                </span>
                <div class="projectTitle">Система ГРОК</div>
                <div class="loginStatus">
                    @{ Html.RenderAction("LoginStatus", "Shared", new { area = "" }); }
                </div>
                <div id="menu-container">
                    <ul id="admin-menu" data-url="@Url.Action("GetActions", "Menu", new { area = "" })">
                    </ul>
                </div>
            </div>

            <div id="main">
                @if (User.Identity.IsAuthenticated && !User.IsInRole("Администратор") &&
                     Request.RequestContext.RouteData.Values["controller"].ToString() != "ScheduleTemplate" &&
                     Request.RequestContext.RouteData.Values["controller"].ToString() != "WorkDepartmentUser")
                {
                    <div class="main-sidebar">
                        @{ Html.RenderAction("NavigationTree", "Shared", new { area = "" }); }
                    </div>
                    <div class="main-workspace">
                        @RenderBody()
                    </div>
                }
                else
                {
                    @RenderBody()
                }
            </div>
            <div id="footer">
                Все права защищены: Bell Integrator &copy; 2013
            </div>
        </div>
    </div>
</body>
</html>